# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal
    - name: Publish
      run: dotnet pack --configuration Release
    - name: nuget login
      run: dotnet nuget add source --username lucasfm95 --password ${{ secrets.PACKAGE }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lucasfm95/index.json"
    - name: nuget push
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE }} --source github --skip-duplicate
